# Change these first
owner: BeeCorp # Your GitHub username
repo: upptime-verifli # Your Github repository name

# Add your sites here
sites:
  - name: Verifli
    url: https://verifli.com
  - name: Verifli (Beta)
    url: https://beta.verifli.com
  - name: Verifli (Demo)
    url: https://demo.verifli.com
assignees:
  - jvgaeta
status-website:
  baseUrl: /upptime-verifli
  name: Verifli Status
  introTitle:
  introMessage:
